### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by heartnn** [Erimus-Koo/qCloud-COS-Sync#1]
运行后出现的错误，python 2.7.13

**Comment by attmore** [comment]
![image](https://user-images.githubusercontent.com/1621318/29853762-4cea53da-8d74-11e7-8e69-051571ea6bcf.png)
@heartnn  缺少了region 懒得改 直接增加了个默认的gz

**Comment by heartnn** [comment]
哇嘎哒

**Comment by lixuedong1024** [comment]
python qCloud_COS_Sync.py 
Traceback (most recent call last):
  File "qCloud_COS_Sync.py", line 357, in <module>
    syncLocalToCOS(appid,secret_id,secret_key,bucket,root,subFolder)
  File "qCloud_COS_Sync.py", line 310, in syncLocalToCOS
    raise Exception('\nerrore')
Exception: 
errore

**Comment by Erimus-Koo** [comment]
官方示例里省略了region，默认是sh，而我也刚好是华东区，就没注意到这点。  

> region_info = "sh"             
> \# Replaced with user's region. For example, sh refers to East China region, gz refers to South China region, and tj refers to North China region
> \# 替换为用户的region，例如 sh 表示华东园区, gz 表示华南园区, tj 表示华北园区

`cos_client = CosClient(appid, secret_id, secret_key, region=region_info)`

然后这里可以是sh/gz/tj/sgp，最后那个大概是新加坡吧。
已更新版本。
